# frontend/Dockerfile

# 1. Imagem base
FROM node:lts-alpine

# 2. Define o diretório de trabalho dentro do container
WORKDIR /app

# 3. Copia os arquivos de dependência e instala (isso aproveita o cache do Docker)
COPY package*.json ./
RUN npm install

# 4. Copia o restante dos arquivos da aplicação
COPY . .

# 5. Expõe a porta padrão do Vite
EXPOSE 5173

# 6. Comando para iniciar o servidor de desenvolvimento
CMD ["npm", "run", "dev"]